version: "2"

run:
  concurrency: 4
  go: "1.24"

linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - nlreturn
    - revive
    - staticcheck
    - unused
    - whitespace
    - wsl
  settings:
    revive: # default set https://github.com/mgechev/revive/blob/master/defaults.toml
      rules:
        - name: dot-imports
          disabled: true

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/gardener/oidc-apps-controller)