version: "2"
run:
  concurrency: 4
  go: "1.24"
linters:
  enable: # set of linters in addition to the default set (https://golangci-lint.run/usage/linters/#enabled-by-default)
    - gocritic
    - nlreturn
    - revive
    - whitespace
    - wsl
  settings:
    revive: # default set https://github.com/mgechev/revive/blob/master/defaults.toml
      rules:
        - name: dot-imports
          disabled: true
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/gardener/oidc-apps-controller)