# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oidc-apps-extension.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oidc-apps-extension.certificateLabels" . | nindent 4 }}
type: opaque
stringData:
  controller.yaml: |
    global:
      {{- toYaml .Values.global | nindent 6 }}
    targets:
      {{- toYaml .Values.targets  | nindent 6 }}