# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
# SPDX-License-Identifier: Apache-2.0
---
{{- if .Values.gardener }}
apiVersion: v1
kind: Secret
metadata:
  name: oidc-apps-access-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oidc-apps-extension.certificateLabels" . | nindent 4 }}
    resources.gardener.cloud/purpose: token-requestor
    resources.gardener.cloud/class: garden
  annotations:
    serviceaccount.resources.gardener.cloud/name: custom-oidc-apps-controller
    serviceaccount.resources.gardener.cloud/labels: '{"oidc-apps.gardener.cloud/controller":"true"}'
type: Opaque
{{- end }}