# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "oidc-apps-extension.fullname" . }}
  labels:
    {{- include "oidc-apps-extension.labels" . | nindent 4 }}
  annotations:
    resources.gardener.cloud/ignore: "true"
    {{- if .Values.certificate.create }}
    cert-manager.io/inject-ca-from: {{ include "oidc-apps-extension.certificateRef" . }}
    {{- end }}
webhooks:
  - name: {{ include "oidc-apps-extension.fullname" . }}-pods.gardener.cloud
    clientConfig:
      service:
        name: {{ include "oidc-apps-extension.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /oidc-mutate-v1-pod
        port: {{ .Values.service.port | int }}
      caBundle:
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
    {{- with .Values.webhook.objectSelector }}
    objectSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.webhook.namespaceSelector }}
    namespaceSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    sideEffects: NoneOnDryRun
    admissionReviewVersions:
      - v1
    reinvocationPolicy: IfNeeded
  - name: {{ include "oidc-apps-extension.fullname" . }}-vpas.gardener.cloud
    clientConfig:
      service:
        name: {{ include "oidc-apps-extension.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /oidc-mutate-v1-vpa
        port: {{ .Values.service.port | int }}
      caBundle:
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [ "autoscaling.k8s.io" ]
        apiVersions: [ "v1" ]
        resources: [ "verticalpodautoscalers" ]
    {{- with .Values.webhook.objectSelector }}
    objectSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.webhook.namespaceSelector }}
    namespaceSelector:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    sideEffects: NoneOnDryRun
    admissionReviewVersions:
      - v1
    reinvocationPolicy: IfNeeded