---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: oidc-apps-controller
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+xde3PbtrLP3/wUuHTPNOkNqYf16NVMZo5r+6S+zcNjuek50zmToUhIYk2RLEHKUdPcz353AZAEX3rYjuLmCNNJZRJYLBbYH3aBBRi4jm1YYcgMO/DjKPA8GrWePGxqQxr2+/z/kMr/5787vUGv3Rt0jofHT9qd40G394T0H5iP2pSw2IoIeRIFQbwu36b3f9EU1PW/Oafewp35QUQfog7s4EGv19j//V4f+r8/aPe7xz183ukP+50npP0QlW9K/+H9f0QurTimkc9IHBDR5+R2Tn0ySVzPcf0ZCS37xppRZmpH5HruMsKSMAyiGH7AOPHIzAsmZGHF9hxyPycR9azYXVIoF8+V55bvAAGfzuBt4JOnYUSn7gfqkFsX8v3XM5O89b0VCXxeElkiIY2I5/rU1Myz8ftxDLwBidNgsQAC707HxHEjppkzN27xfwX7mjn5I2rxf9MH81kL/0n/ZEu/lROaQPuSkExdjzLtO5PdhvDvxLqBf+MF/g6Ajvbd/0GJd1bkBgkjF2fnUG8YBb9RO9ZM16FWS2SHR5q5ZHbg0JY2cX2NMU/70p28JtXq/+ncimJzZS28B6ljg/53usfDsv73e8cH/d9HskL3HY0YaOSILDuaby3oiNQNCs2hzI7cMOZZT8iPMEUQGwcKmQYR+SmZgMbSGFQohQn4L55TmWcpKjHFK/kX8ZMFFAMcCRLPIRNKXN+O6IL6MeACtew5id0FJasgASC54bR8QCKoAcAqJw7QQlzAo5guQgAfyp4jIS/h8IXZoC0ZB6jG4icjFoAd/RCCEkN9QHIKTQ1uyZguLD927TQjknk6j+OQjVotRhdACkBh1nqmLVPZtc222Sk3vdTMYJoy47m2QMEJRdoODb1gRZ0N0gHq28knlY5Sk1lstB/EasOBcnPTkSu6StkA1PagWKF95VZBGxKGJYHuRYx/RtQGsKW+I+ScMOjqWCD/70kQ4+QCBLKRqC+5PPXHjJxfR6rFfyewzVnwYHVssv96w7L91xt2+gf830dqtcj48uyfxj/A+jkNwhWYOvP4mn6IR6Tb7nbI+OSSjM8JILzl8z+sKRhKLoAsAY0OLX/F0felFTnUB7Dio8idJGCrMa3V0lL6r1yb+owaF5AtdqcujWASActyTo2u2dYg3ywYzZAEkmZzYthEN80W/DcH+6yVvlKGqRHRmcviSOAbm+tIBcxZbq3KmYH61gTMOlIgLsxXPm3Jh+k8YQdRhOCWV0IKlWihSv1rQKda/c/m0YdZCdjd/+8Put2D/7+PtKH/34OHB14YM+Pw7r7ABvwf9qDPof+7nfbwuDcYPGl3251B+4D/+0hH6+C/dz/4P9KOtgJ/wzC0jx9b32nnH0KkhkiMjkhqMHOwNbXvWp8+QT4DzOWp61Oi52MXGIYKEKGxnE6MPKeVeDExhUf7Boma7ywvAYMTc74FCzYC7538SeIo8W0yOOY/3cU4gYZ+ILqhE0kLjFf8KTg9jSjKwMpqmCaetwJb1vKwfQ73OLAGU/uFCto8f4w1YHsY2PO2hXYwC4Cp3H0SLQcaniNMdc9duNI9idE7eDpZcamcvRljXpy6GBjyz0ztYoqLL9RiUnzYGZYLFr+YC/kzbnV7HvpaUDnwCZVw5iW3WwkZ8xcF7U4zuaYvM9nKLI3vt5G9xzI63/B2jF5s37k5j5lEBBHzSohLlE35LDzckbkwcv14SvS/MeNvTC/REpVuP9TqfxYGoNKzqDmpQ2Yx0btyqIhcnjWh3pY9zEvk3Vtulipx8Vu6btCkCJxZywa6/60T/b2+u2qJVTnOLduOW5FXsItL12AMtngLRuTjR7kUsL6hpmBlfV5G0fMNoleyOlMZWVIMJ5kTi++gvHmTabbpBq1svQDqqhb5UzjDJbFUqYCLDkaoY0xWglA6ysY0WgLU1op1LJnfSbDlFhu17IhFo03SE4Bh1rcIdDK2fJsW26OqZXGM0AjnEY6pu7THzsupTdrEuqd2eJV5nAkDH6a2EVEqaNTZyvSmNIZRO6KxXCLZuU1jXvpNEzIrOU1b8JJiqsTSnAACbFntn64VUj4pmM+Ifksn8yC4MWIPLEuqYkkK2zV11jHK8tc1eJsS0+UPgJw1KFrpBlX0EZ3SiMIY5I4hf2sZrv8bV4Cdu+KKTuvgs1WZFViIYLletPCKxTS6Cjz6JpWwsaFp6ghjEhcs2w4Sf7fhJcueiKKNY6uYrTS80l7aYQA10PW3HgfbENg8QAp6KnqBgJNEd9PQcvd95fK7onGCG4oWiMwFWLzghgijYJBg8S1tTBrb81NZ/ofVGErn7gPXcUI4dIk6UsyaAXqmrM+kV2Ji1abl+0HMl3GYUqOZ1ajkt70gcVqCsCFEWq7v4gxr05UXES695xDGczHxWmSA3qa/EyFBlWuZpUz+BTEz8RmFPBMYHDfZM0X8NX9E9PfEjUDyTzkIEX0K3Qj9EJCsIoQ7lNCI6A2i4yw/U3irgo9Bst50F2Cc6JI/2fC5xS75fi/R2dzq9gejvC6e34ytWc51Dph/54BZyAkGZsBcAOXVOhLp6C4THN2ZYHm0f2nX/UHShvUfdSa+837wpv3ffrvH1//7g87guNvD9Z/hsHdY/9lHejzrP5tMVeF75LvVmMUQnlDEXauOduP6gGKKc6AtaGw5VmyNQIm3c1OUWVTovp8aaVXfRNhuPJdwEUY52K+156puiAnOnw/sg4BID0nimg6Sc3zGqxKkjR35N9nSvlvBjx+rTf089FL7yPQC2/KAustYAuYSnYo2i1694A/5g+06smo0i57KHYotaNT7VubXMxFsj/+iV+4yC2za/x0M+jn+Y75ut9s7rP/vJX2F+C+R4q8P/Yx607E789E0//iZAGeT/gsQRZf3s9l/3eO2iP8bQKbjYRf0vwP5D/q/j/RY9T+fvJv0P5pYtmkl8TyI3D9EeMbN96xoCeZU7gAHTQbETvruNSl5lHjCqDMItOplFCQhG5FfcUnh35x0RFmQRDYVT+UyDNOf68KAwV90iWsMaYEljSYi83fiUZkyslZPXQQgLjg1qCAGeQMYMl4L0XFHBxCL/7ltXT6Nb4PoBoMARa/UVwzv4QGj2xOup5MhNWc4DJwagjMaQ+M8l+H/bjEuvb4GOwgix/XVIVVfKZ8NtuVct5wFmFBAsxBRJOlXyeuLJOaBSXIlHTRr6s4SUYzpWzTuuZ6EMOJpw2AAHWVgb2/qoSVOWJAPZJoWAQ3cttGNq2t1LZYKt1XjeGVfhwn+RdP28/8E0AsHy+5mwMb4/8Ewt//73P7vdQ/nf/aSHtn8j8TW2ADrd0vuZyH8IMb3Q/gND2QhAFNyESTF1DVt0tKFEtXouZ+pw5IJ7n5KK0VQHxckryzHbKyjbiPRTDc/tvO0Dnj/4GkT/qtWx109wE34D3if4/+gjf4fTgMH/N9Deiz4XzqHloINejp/4ZWceBXicbrQ+j2hGtj8ML+cyYbk6sbVakT+5NUWFG6kbPrGwb8gWz45qvmUagcposKoBrOZrSEhc5BS6S89Ig9pn2kD/ucLA/c4Drwe/zu9wbBTjv8ftg/r/3tJjxH/cTjmJvpZNgQf6UTQaMBj6TkI1LCWlgu5QHDxyhDIbWYrH+WwIzFnoLVMo2wrIF2C41ynwVrdDMrT1+kOp4jaFfzzGxheKQ3aoknVSOfKDJNihKxE6RlMSrBV+gjmtjm1b1iyKFqVhU6UUUrfmNeSvPkDdM8l3iSh1xij+jPOmggpAsp5LJVoJD9gnAopDJwTJQaslDWdHJWWfl/Ok0VWKWLM16xBBpFrM1OcORzbEYxpf6YWCKMAMs1pooRN6zUBz3pDCYY0sUwcJbQpE55tlGRLjPFTjyr1Spu8wjC550ApiE9ZDy6P98BwYJQQC8+fU2e7EjBMlngaVGbauXgyAX25a+kI/Fd3QUEWrlDTYvlUZ2sHIQ8suwRUEratMgzLb0Y7DM9KR1ad7c1YudZBB5UGUF/gm+ISwHVwQ0GHcURmddtJBEh3CnMBziS17ch1clzM3tzA0vIQDIGAl/MsxuqfZtGqqZ4o7zKZrCmpnMdokLM8UAQzV95MI5+b1IMyijKskVGDnFijkDrdImU+jIqdLQMyzZqMON4uA9CFVUEWIvwxzF4WS1J/WWQ4bfGbk9fn48uT0/PCW0KWSPUfgFKj0gsiDrploT417xD7R9n8Ymbzd0ViChJz9t9xYMJDYLcguZL8c54vXp+8PH93fnr99ur923fnV79cXVzX8j8i4kwRex+kNFu8IuUBn5QqnJWmjRqGU4xpYvLlydXZ+Zv3J6en5+Px++u3P52/qWdRby2tqAUA1ZK7hK0SfIk/W7n+WzbYIMyIUY31dZWPz8/P3p+9fX1y8eY9dnQDA8ooKgYRIyyacr/PdIIFqE1hMkrF8k0W9Tx6scG4Wx8ibjYIPa9gvbR5g9+e/Hz9Y/f95dXbf/7r/emri/M31+8vzurbDk1vpL1mHFQeg1/OVH0wiG4Yf1ih4dAl9V4UJ3/ltRfMDI9n6VbeC9vpRQtE1iotPVTyJmCqq9E1L5Q+rT1DVKGQnv7B3Mxw3EhULB83Zkfxv9jNpG+khcaOyric3YQR9CdBK7NYug5DaifqNDOf158iDH9oLtV+VizIeZQ7wCtDKCln0y+bfg2Do/GhGj2BrlV64G8cRzUs8CxGar4VerhaeCumdrKEJRcyY6WzChZrU2dVuPDcJcANY5dRMKHFCQUvb3pJ4/IsE/LJpTWnlhfP/yi/5Ib09+3vO6UXDASEOPHj9fVl4ZXru7FreWfUswCNQM0cMC0H7UKekIKd4WRvO+pb0CfHvVMLsOTqMzWgrxVJsvrJXypeqarMQLoM5HHctQpZbkEUxIEdeCNyfVrk9A4jLmdV5t6a1drhuBOrlbGaBz5sMv2ynGuMvmXgJQv6Gu3xSu9wm11YUSoIl9gXguF4vaF8afaop6N66uXBl0wEtXWE7mHQZTOFwUsteSkjM9FK3Kitq5h3pbyoZHhHZcHbyfm9v5lXb5Wt4fg+xt56/iuOqx842ayQZ1Of3sthrdSHC42ARorrkT552HriwKNReUlIeXiv2uIgDMAqW41DHDvgvGHcl1tQUlAw68P4ht7CXKB0SVryJwrDrXjcfB6wmJ+jzHPjha0/+ww4ZlMXEXBExoDxTuLRE391a63UWRKXaqp9xodWdalQbfydV4I6vVwkAqpq3OUi9mx1dD1nT17FSp0i37UYi1UKhalzOrcMmFhzMERtQn4KMU10EcarM7cseeq4yWJEXtNFEK2KJIqwYmyA2LqW7XLkpbJiXtsfmwB5dzAW7XlthUXW77LMvwXwyyX01wBfI9LrttdJfAsQ3xrAN/XOBgIKdw+0/7Nh/0+R5Oc7/9nuD/L4j2GHx/93D/f/7iWt3f+75/WP94j/b8KX2jCR0xQ67r1B2Igcu28b3vWanBr83fW6nFQCtauTGGhSXuktCxpdnHwb8+FB55AeTdqA/2HgOC6LEn7t9yRxZvQOgSCbzn8Oe0r837CP8d+DQ/z3ftJjjP8I+Z5THgFyGThn2SD8gQ/CvYeC3CMMJN0PBj/vZ1+GgqCHhu7eHkI11vf/Jv2Xm6I23xT9TPG/nX470/9eG+O/Or3O8KD/+0iPRf/vuMGfrwWoAMLE2kd+tE3BErV4PYpsCiXY0spTryK9qyWXbyxm9zjp9ezxnOJLCyKj3tAOkRFo42d7cKmfO8IjMrU8Rosf+dBTYRGu/tm9eFlvZyhU12BTP1iOjz9twP9spxIUjSsvjJKdp4FN9l9/mNt/vc4xt/8O93/vJz0y/E8xxAnsGxoJx/5/WXqb7i5HRPKBDWMYR++WFp8Ivy2CtOBGrFD+BtxkHrZZflMAwrpGPLYjbBv0HyN3ZJTC51v/6x4f5/rfbfP4/87B/9tLeqT6ry6y31XvSyvoX+gIGBJqjPUPkygMGHDEmTTQdqMMrxteW4pbYyMinmo1wfYytEJe99t81EDuJIEKBAuj9qNvu1BLPeVvPyrXq5ZZz0jrIxHF/ulbCblvxSm5xwaQX3naiP8iSOde34LcgP/H7R7H/2G3PRi2uf3X7hy+/7if9FjwvwHk+ej76537qiCycp6kET+nEaAw5PIcA4+o8Eg78u2vH/U0tAwg8/r0Un+u4zt99PFjXSjdp0+f/v1t3oBtQ+S2ZtDyPENYhfwwkiFPERvyBMxOfKtxdTnfW7Mi1om/YM1h4Bh8FGSBtPwkUJ18sh5Rggu2qS4bt1kVsonKWjE0TC99IEQ9LgFCEET1nRpabZyRM2MBBiAj+f1OSLgSXJUOTKt87g50sCaUqle+5iNbOxcmQk30KL4QpZTQVEOGvm4ZbSq6SER9FqMj64I6q9GuOylaDW/rwkubOVCDWAsDq7incK8NhN5h6e4rT9vZf6ntfzczcHP8T0fx/4e4/9M/Pqz/7SU9Fvtvq8+hlC/4KhuK6a1Uu9uLa86+7tdybJpCU0lUZtKKqdkQplydW7c40HvYwPna0wb8X4bW/Xx/TBvwv9vu9Uvf/x12h4fvf+8lPVL8x3En7GenhPk1F9e2lh1dTgTv5G21l4Fzkt1W+1dbP8icHu6XZIfj667IweeVa3JyH2HnZlamH+wIcY2wehOA+mS0tTOXL2nLkpxT5dgdPHTz0xpG/io7uvBNw40KtXwvXP9ErA2oWfOnTZx32ltc/FKtzfpQV1v29F61lVQjw2pHPFSzl98VXM1Nhes/6/alQeqQPlvaMP/LZY7Puv7f67aPS99/aHcO93/uJz2W+b8wua25KT+P5Hst78f/RQzR08J5uEdziXONg9a44urO/CAqXu+19THI8tdwxIdrDdsycMF6pwON/NO12eETZRqQYCDvg77T+Rr8MkOp2YJ9fm2K6MN0/peeb35Y7s4HaNLCmw04uegqTldz6vwzDNRYdpD3PMcu68u29UPiO55sSfbhD2HjBGF20hg/dXB6dX5yfY4fsfj58gx/yQ8tSAOw5kMYRdNQfrSho74tftBB/ThGxZBJ8T7gN3+Xz3sXn65dbhjUjJ+1NWb9U6608uJO9TLXoefTKb/OnLwJfPrWP4tWV4k4W5khzhVduvQ2k2XWS9LUjqjrLwOb91dq/V5M31Dq8PiyOyoFGGV/WaUA3h+TUjR/1WRXNVn/3ZOD4jyc4nxpE+g/OtXa/0sxwu698CfTevu/0xse90rrfwNwAQ72/z7SEZEnQMQlduKQR90MomniZkm+ipN+L3tEaBIBWBsi1NkMb2amQ5fZPTSGvJejFYmZJb+hppVHDrQaIg9D5W5KwIogvgSEFutbRwQPK0cATYyfSOGsEfxc9+08YDS7IdkVr/nFPrhmJvHJ5ItrM7C0l22zYx7rsnHq7avk139riKBpRZBZ19JptPBQy2WY3cPMd1KyAzN1DST51epafrtzV9OKGz4j3tpxSG30mxje9AIUwR1LLQEi92YJmweJ55AJNJd7BmhDiF/ZfUVHRL0AOQ4Avh38H/JYIldyXPD7k1j+GnLy8z3BtK4UEkvAgOB5L6YECECWmPuI0l/BLgFunkMLOCH4e4YDAjmGshgpgYRTSWf3TGeOHEpc8VaaBaRkqgoHvaqSz4SshGKIgakiBo74Lg6v4pc59cUpqefNnSqos+ckQtEBO9hysVoqhqKctVXmmKn0lDiGVSfqQnP4IL2DtOOUKLyQSkKzIZDJnNsZenaVYuwxfpOjTlgC7v8HrXBnCfRG/vWgNb0hMhH8qtF2Y7UiAJXC5x9omla8MJzrgFa9sJg/PyJTJr/Q1IU5DbW4LpNtheIaeL7MfQSGkQPwKX4Z5OTVK/iV3jJ2BRMOLsuwFbR6IeUCrxP/hIEdhq+LD39muK7SkdVnboIInZJfhbq41FI7vdPu9ts1aq4Vrqbz3IWbhlUt+OVEI9J/6fJZgAery3d2mADJRTFf+7WraTJOCbMVI6Kyrs7uKQTGC4cVxWiqqoY8FglN5X+WA/+VWUQD/ySv2cmqLGxgcKbFE3EhkI57RzqnDUVBkDG3cPnBSv6RzJF8h71W/IRhmKCbIiTAv2N4JL0LmIP8GVWIjMg139/50Z2BhlzD6yspUa2wSVEQaRdFikSVfQVZCe8BGHwL+XdWpD/gZar7Aml9ONo0rXCVGw4E9RI0nA2z+9f4KJHggLWXvBsxV1S9D14MpqAsQI2IL+LANIktwV94ySUbtVpoR8wCbkrIZT8YMQvLnuNm0Apfy9MGf4cJvPs/Zvfo0opg3gcfFQa5/xyqAXTgwGbzS9cSOxYYkg2N9BZ3IicAwu89NWGGFFd0pcyJ87ISK1k2W8aANGDKoE5XSQpSWvkm1RE2/+3F2Sk5gWFKzlMLiBTXLo9SZTVuwcTID9nyK7K0ygeCJMnLKFj+f3vX0tu4DYTv+RXC+tCXZdmJ7dq5uUkPxgbIIsbeVy8nQmTJsJxXjfz3fvMgKSmui6LA7kU87DoSNRwO5/ENKZGovmsSo6MR6Kvh6I1eTDWHAh0Lb9Am2XAb4CUsyDWbfWPQPD9P7ZPXT5UMjTydRHeOpl/VipSZVQxQKOkj/YJF4d8iSyDaMNMNh7WqTHJ4y+sWq0Ka3n98pUDS5LhPlVEpLncwv21Z2BgGB0BQam/k5SShFMhNEFUWVm2aZZkwtPjImcbaH8Vdz4Nfr7wvn6/+NBxR2zSRroRo8z8TAGsdEiDb7hT6AP8Da/h6d/MD+7QqYSbMkLlRAVxseaLoJcuTGLZVWXfw64BOPeEtw3XhNxBmgxg8RWH8qJMM0revu7zdbdOKh3tOrIkHqB4S6AOqof4MXtI89x+L8qUIRGP9ZpeSDAoNu3jj6TCZ20H35Mj5ertVlS8LBgHp6jGjxCNbv7kYRlvtyt1bPE41hATXU2meqg0AENdCIr39fQc5NCyRLoozEGeIYaZLPh0hSYnZ6xv7R0FLKznrccHfzMlkjmeOmSQ3mBVxuaEfOxek2G0YP7l/CHnocnIdG3hjqIt44FAVMt4kA+Xnn/28VPXvy2BflnkV2EcpAgTPo55Q4NZdB8m5uhFfgMl1ukshImlfTVhfJyBu6VHVVpulfSbh3P2xYF8K4RwRSeVcHyNUevkcFpE+jwZibne2YdPFe2Dpp2gA6QXuHX3uTJSXUUDxazaAIoMKusen/1SQSe9mNByNbTctdYqiBHl5qYizmNowuwRGGSRknAkCZxBNuTFXYmtIuNttnXiqNFWRrgKdJT9VH9JDiRkEpyrC01cLL+LpXDL6bbohoW6gECYKP7P+25QR/GS8Fog4C8bIRM/Ekq4WOi0swylwgUePk5I4HMRwEY/pm3s5RJhtM3L2vQZIuD4xQPVuNYeod/3EGnqElWgXFvFfQWtwgoy8RBWcT+Ye/2Tlhbvy0qw5yvsXzmdDgjcAtkCCXsnbeujIJXCvyP4zuhTmuthpXLobeZsVkb3brZDej9IIm3MLJwi1Uo7/RUvyRD1P4ijaQSUXO4DBaicj9hSDe7qfri7gGPN299yRI6pUtMAMpbqpb6b7X+ArnR3En+mQT2tQOTV3b3mSofiODB3ZNVgkj5wgNKJGEoVokIYbTun6XskeGJU0aLBGOvBC8Rc4woSZNBkw3drnOP/ejn4e4/1MXe1zf38xT91e314a1N+ExFAOgzZI6Sh8Wf/h9rmxrcAgN0+FhuU6j+bjnObg6CEnSDpp55Rtmak/1utmccTktT0X5mtECJ8JMOlrGkMSKyhWq0E4pe6TmyEE2PbdhwMp0vu7Lz9Yo+wKHO0j/YVbsLGz1j7dtZIwPUIzSbaGB/XorQK+dTg4Ou/v3m+44BhrtHXZbsJQrRt7u8XWt+huXM34FfdZ8WrPlWl+BkfIMC0S331E9YmOPFh9ItynKR1LF7oZRnlWPYjFGAkLyNS4SAthgKXKxsfJUWXuZqV7E3BXICZKISpobroDfqrv1rzPKxc1LIHbrbpAHUJGz82T72zd5d4maTruZo6MM8fDofGcW3ptppBIOJeA7mHFM23mVR4A/jSFU96AoH0iRbKRxQ+1pA2SApKSMM/t8w1StsEZGy4DCkkUrMg4fn9zmwS4tYCPWx0wHCR630APqc5OiNn9ruiPvLynpdrWbCE9iSSc/1dvbxbo0eoIf96ceE4nVWxuOBpeTCfrWewn8yj0x+P13J+ls4n/+3iUzuJ4OFrPY5qsMuf/iJeJUpcCqWyQBVtxwvntj+ZIDVbPW8x4l958Fl5Mo+ncn07m5/54ehH60XQ48ZNxPJlerGfRcDTtXtvsSle60pWudKUrXelKV7rSla50pStc/gb1s67IAMgAAA==
  values:
    replicas: 1
    priorityClass:
      name: gardener-system-100
    clients:
      - name: local
        clientId: local
    image:
      repository: europe-docker.pkg.dev/gardener-project/snapshots/gardener/extensions/oidc-apps-controller
      tag: v0.6.0-dev
    imagePullPolicy: Always
    cacheSelectorStr: "observability.gardener.cloud/app in (plutono, prometheus-shoot, prometheus-cache, prometheus-aggregate, prometheus-seed)"
    webhook:
      objectSelector:
        matchExpressions:
          - key: "observability.gardener.cloud/app"
            operator: "In"
            values: ["plutono", "prometheus-shoot", "prometheus-cache", "prometheus-aggregate", "prometheus-seed"]
    vpa:
      enabled: true
    configuration:
      oauth2Proxy:
        sslInsecureSkipVerify: false
        insecureOidcSkipIssuerVerification: false
        insecureOidcSkipNonce: false
        oidcIssuerUrl: "https://dexidp:5556"
        scope: "openid email groups"
      oidcCABundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lVT3B4dzVnS0MxdDdYdW1abVVzNENIZW5kek1jd0RRWUpLb1pJaHZjTkFRRUwKQlFBd016RWVNQndHQTFVRUNoTVZaRzlqYTJWeU9uQnliM1pwWkdWeUxXeHZZMkZzTVJFd0R3WURWUVFERXdoTQpiMk5oYkNCRFFUQWVGdzB5TkRBeU1qSXlNVEUwTURCYUZ3MHlPVEF5TWpBeU1URTBNREJhTURNeEhqQWNCZ05WCkJBb1RGV1J2WTJ0bGNqcHdjbTkyYVdSbGNpMXNiMk5oYkRFUk1BOEdBMVVFQXhNSVRHOWpZV3dnUTBFd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdElNR1R6cnN1cUdCbXByKzdidVdEU2o1Lwp2T3FwbDlwNWhsTWNUaWR1eHFpNmtyc2M5VWZDbmRKeEUvV0hDZW1POUlqWXRTVWtBeUtvSThuZjVTVlN3Q01rCndVZWVmVGVnK2laVUpseXdvTitGWHZUL1Uya2lYSXRDV2hNUUwvWmdjWS81OVROS2FCekdJZkY3MVY4TjVsM0kKSkVTbEt2UFliMnZvV2pYNXdiV1JteEkvSElTaEhaamhBK2htSkZBM3BBQnBQZUFvcmYvanB0YUxIdFgwQk44Qwp6N29uMmdYTzdsUVN2Sko0Y2F0SHdXeFRTQjhPRncwNXZiQzBTaVlmVVdUSmc0bFJucTZhazhicDFBd01TVGpIClUwMGJzU2ZXL0syeVNmSVhMMENHdFVvbG45K05icjdIU3ZvbHRYaXp2MWd1UHR4ZFV6V2t1ZGlqc3prckFnTUIKQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRVwpCQlRIZ2lvcjhzR1hweHExTCtwblpqRS9wNTl2M2pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWxBZGVwZjZICkFNSjFMOWliT3JONjV1RmVISFJPUTZTR3BjUURxdXBqUG1CU3Y1SGJsb2kreTlWalE1eDQ2dUtRdGoyTWJlTGUKVGhrRnA5ditsYkk3U3JqRjd4R0tOckVHcVJzanJzdGhmb2FDdkZQU3QxMWEyd0ZGeHdsVmsrTzNPWmNhRERaRgpNbXdGbmJmbXB2bHpyZzN4U2wxVkdnL3BiYmVzTGJoNTNyQk1ndldkcU5JYUtIWExoYXJSMXBYb1A3NjR6czhECmFQcnc4bFNxaXZqWXJJelZVUzllUDQwQTJLMU5vakJQVlB0dldXMXpySGMzb1c5SVZOS0EvaXFnMGNMdzYwN2kKblJ2NXdDcFlKTThKTDVYZEZ6N2NPTXNNUEUxaElYU1RDUnB6QnFZeUFFV1hEeXl2d1RmMHJBQmZzTDlzUVVQRQpYOTZFVVJsbWVsRW1nQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    targets:
      - name: "shoot--plutono"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "shoot--prometheus"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "garden--plutono"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-seed"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: seed
            role: monitoring
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-aggregate"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: aggregate
            role: monitoring
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-cache"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: cache
            role: monitoring
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: oidc-apps-controller
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    deploymentRefs:
    - name: "oidc-apps-controller"
    policy: Always
---
