---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: oidc-apps-controller
injectGardenKubeconfig: true
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+xde3PbtrLP3/wUuHTPNOkNqYf16NVMZo5r+6S+zcNjuek50zmToUhIYk2RLEHKUdPcz353AZAEH5Io21HcHGE6qUwCi8Vi8cMusAAD17ENKwyZYQd+HAWeR6PWk4dNbUjDfp//H1L5//x3pzccDNvt/qDTfdLuHA+6vSek/8B81KaExVZEyJMoCOJN+ba9/4umoK7/zTn1Fu7MDyL6EHVgBw96vbX93+/1of/7g3a/e9zD553+sN95QtoPUfm29B/e/0fk0opjGvmMxAERfU5u59Qnk8T1HNefkdCyb6wZZaZ2RK7nLiMsCcMgiuEH6IlHZl4wIQsrtueQ+zmJqGfF7pJCuXiuPLd8Bwj4dAZvA588DSM6dT9Qh9y6kO+/npnkre+tSODzksgSCWlEPNenpmaejd+PY+ANSJwGiwUQeHc6Jo4bMc2cuXGL/yvY18zJH1GL/5s+mM9a+E/6J1v6rZzQBNqXhGTqepRp35nsNoR/J9YN/Bsv8HcAdLTv/g9KvLMiN0gYuTg7h3rDKPiN2rFmug61WiI7PNLMJbMDh7a0ietrjHnal+7kDal2/J/OrSg2V9bCe5A6toz/Tvd4WB7//d7xYfzvI1mh+45GDEbkiCw7mm8t6IjUKYXmUGZHbhjzrCfkR5giiI2KQqZBRH5KJjBiaQxDKIUJ+C+eU5lnKSoxxSv5F/GTBRQDHAkSzyETSlzfjuiC+jHgArXsOYndBSWrIAEgueG0fEAiqAHAKicO0EJcwKOYLkIAH8qeIyEv4fCF2aAtGQc4jMVPRiwAO/ohhEEM9QHJKTQ1uCVjurD82LXTjEjm6TyOQzZqtRhdACkAhVnrmbZMZdc222an3PRSM4Npyozn2gIFJxRpOzT0ghV1tkgHqDeTTyodpSaz2Gg/iNWGA+X1TUeu6CplA1Dbg2KF9pVbBW1IGJYEuhcx/hlRG8CW+o6Qc8Kgq2OB/L8nQYyTCxDINFFfcnnqjxk5v45Ui/9OYJuz4MHq2Gb/9YZo/w17/aEw/Nvwx/EB//eSWi0yvjz7p/EPsH5Og3AFps48vqYf4hHptrsdMj65JONzAghv+fwPawqGkgsgS2BEh5a/4uj70ooc6gNYcS1yJwnYakxrtbSU/ivXpj6jxgVki92pSyOYRMCynFOja7Y1yDcLRjMkgaTZnBg20U2zBf/NwT5rpa8UNTUiOnNZHAl8Y3MdqYA5y61VOTNQ35qAWUcKxIX5yqct+TCdJ+wgihDc8kpIoRItVKl/DehUO/6zefRhVgKa+f+DXrs36BwPj9H+G3S7B/9/H2lL/78HDw+8MGbG4d19gS34PwS0x/7vdtrD495g8KTdbXcG7QP+7yMdbYL/3v3g/0g7agT+hmFoHz+2vtPOP4RIDZEYHZHUYOZga2rftT59gnwGmMtT16dEz3UXGIYKEKGxnE6MPKeVeDExhUf7Boma7ywvAYMTc74FCzYC7538SeIo8W0yOOY/3cU4gYZ+ILqhE0kLjFf8KTg9jSjKwMpqmCaetwJb1vKwfQ73OLAGU/uFCto8f4w1YHsY2PO2hXYwC4Cp3H0SLQcaniNMdc9duNI9idE7eDpZcamcvRljXpy6GBjyz0ztYoqLL9RiUnzYGZYLFr+YC/kzbnV7HvpaUDnwCZVw5iW3jYSM+YuCdqeZXNOXmWxllrXvm8jeYxmdb3g7Ri+ad27OYyYRQcS8EuISZVM+Cw93ZC6MXD+eEv1vzPgb00u0RKXNVa3+Z0EBlZ7FkZM6ZBYTvStVReTyrAn1GvYwL5F3b7lZqsTFb+m6QZMicGYtG+j+t0709/ruQ0usynFuWTNuRV7BLi5dgzHY4i0YkY8f5VLA5oaagpXNeRlFzzeIXsnqTEWzpBhOMicW30F58yYb2aYbtLL1AqirWuRP4QyXxFKlAi46GKGOMVkJQqmWjWm0BKitFetYMr+TYMstNmrZEYtG26QnAMOsbxGMydjybVpsjzosizpCI5xHOKbu0h47L6c2aRvrntrhVeZxJgx8mNpGRKlg7ZitTG9KYxi1IxrLJZKd2zTmpd+sQ2Ylp2kLXlJMlViaE0CALQ/7pxuFlE8K5jOi39LJPAhujNgDy5KqWJLCdk2ddYyy/HUN3qbEdPkDIGcDila6QRV9RKc0oqCD3DHkby3D9X/jA2Dnrrii0zr4bFVmBRYiWG4WLbxiMY2uAo++SSVsbGmaqmFM4oJl20Hi76ZesuyJKLpWt4rZSuqV9tIOCrSGrt9YD5oQ2K4ghXEqeoGAk0R3G6Hl7vvK5XdF4wQ3FC0QmQuweMENEUbBIMHiDW1MGtvzU1n+h9UYSufuAx/jhHDoEnWkmDUD9ExZn0mvxMSqTcv3g5gv4zClRjOrUclve0HitARhQ4i0XN/FGdamKy8iXHrPIYznYuK1yAC9TX8nQoIq1zJLmfwLYmbiMwp5JqAcN9kzRfw1f0T098SNQPJPOQgRfQrdCP0QkKwihDuU0Ijoa0THWX6m8FYFH4NkvekuwDjRJX+y4XOLXfL9XqKzudXtD0Z5XTy/GVuznOscMP/OAbOQEwzMgLkAyqtNJFLtLhMc3ZlgWdu/tOv+IGnL+o86E995P3jb/m+/3eP7v/1BZ3CM6//d9nDYO6z/7CM9nvWfbaaq8D3y3WrMYghPKOKuVUe7cX1AMcU50BY0thwrtkYwiJu5KcosKsa+nxppVd9E2G48l3ARRjnYb7Tnqm6ICc6fD+yDgEgPSeKaDpJzfMarEqSNHfk32dK+W8GPH6tN/Tz0UvvI9ALb8oC6y1gC5hKdijaLXr3gD/mDZh1ZNZpFT+UORQMa9b6V+fVMBM3xX/TKXWaBbfu/g0E/x3/M1+12e4f1/72krxD/JVL89aGfUW86dmc+muYfPxPgbBv/AkTR5f1s9l/3uC3i/waQ6XjYhfHfgfyH8b+P9FjHfz55rxv/0cSyTSuJ50Hk/iHCM26+Z0VLMKdyBzhYZ0DsNN69dYM8Sjxh1BkEWvUyCpKQjcivuKTwb046oixIIpuKp3IZhunPdWHA4C+6xDWGtMCSRhOR+TvxqEwZWaunLgIQF5waVBCDvAEMGa+F6LijA4jF/2xal0/j2yC6wSBA0Sv1FcN7eMBoc8L1dDKk5gyHgVNDcEZjaJznMvzfLcal19dgB0HkuL6qUvWV8tmgKee65SzAhAKahYgiSb9KXl8kMQ9MkivpMLKm7iwRxZjeoHHP9SQEjadrlAHGKAN7e1sPLXHCgnwg07QIjMCmjV67ulbXYjngGjWOV/Z1mOBfNDWf/yeAXqgsu5sBW+P/B8Pc/u9z+7/XPZz/2Ut6ZPM/EttgA2zeLbmfhfCD0O+H8BseyEIApuQiSIqpG9qkpQslqtFzP1OHJRPc/ZRWiqA+LkheWY7ZWkfdRqKZbn4087QOeP/gaRv+q1bHXT3AbfgPeJ/j/6CN/h9OAwf830N6LPhfOoeWgg16On/hlZx4FeJxutD6PaEa2Pwwv5zJhuTDjQ+rEfmTV1sYcCNl0zcO/gXZ8slRzadUO0gRFbQazGa2gYTMQUqlv7RGHtI+0xb8zxcG7nEceDP+d3qDYacc/z9sH9b/95IeI/6jOuYm+lmmgo90IlhrwGPpOQjUsJaWC7lAcPHKEMhtZisf5bAjMWegtUyjbCsgXYLjXKfBWt0MytPX6Q6niNoV/PMbGF4pDWrQpGqkc2WGSTFCVqL0DCYl2Cp9BHPbnNo3LFkUrcpCJ8oopW/Ma0ne/AG65xJvktBrjFH9GWdNhBQB5TyWSjSSHzBOhRQGzokSA1bKmk6OSku/L+fJIqsUMeZr1iCDyLWZKc4cju0IdNqfqQXCKIBMc5ooYdN6TcCzvqYEQ5pYJo4Sui4Tnm2UZEuM8VOPKvVKm7yCmtxTUQriU9aDy/oeGA5oCbHw/Dl1mpUANVniaVCZaefiyQTGy11LR+C/ugsKsnDFMC2WT8dsrRLywLJLQCVh2ypqWH4z2kE9Kx1Zdba3Y+VGBx2GNID6At8UlwCugxsKYxg1MqvbTiJAulOYC3AmqW1HPibHxezrG1haHgIVCHg5z2Ks/mkWrZqOE+VdJpMNJZXzGGvkLA8UwcyVN9PI5yb1oIwyGDbIaI2c2FohdbpFylyNip0tAzLNmoyob5cBjIVVQRYi/DHMXhZLUn9ZZDht8ZuT1+fjy5PT88JbQpZI9R+AUqPSCyIOumWhPjXvEPtH2fxiZvN3RWIKEnP233FgwkNgtyC5kvxzni9en7w8f3d+ev326v3bd+dXv1xdXNfyPyLiTBF7H6Q0W7wi5QGflCqclaaNGoZTjFnH5MuTq7PzN+9PTk/Px+P3129/On9Tz6LeWlpRCwCqJXcJWyX4En+28vFv2WCDMCPGYaxvqnx8fn72/uzt65OLN++xo9cwoGhRMYgYYdGU+32mEyxg2BQmo1Qs32RRz6MXW4y7zSHi5hqh5xVsljZv8NuTn69/7L6/vHr7z3+9P311cf7m+v3FWX3boelraW/Qg8pj8MuZOh4MohvGH1ZoOHRJvRfFyV957QUzw+NZupX3wnZ60QKRtUpLD5W8CZjqanTNC6VPa88QVSikp38wNzMcNxIVy8drs6P4X+xm0q+lhcaOyric3YQR9CdBK7NYug5DaifqNDOf158iDH9YX6r9rFiQ8yh3gFeGGKScTb9s+q1RjrUP1egJdK3SA3/jOKphgWcxUvOt0MPVwo2Y2skSllzIjJXOKlis6zqrwoXnLgFuGLuMggktTih4edNLGpdnmZBPLq05tbx4/kf5JTekv29/3ym9YCAgxIkfr68vC69c341dyzujngVoBMPMAdNy0C7kCSnYGU72tqO+hfHkuHdqAZZcfaYG9LUiSVY/+cuBV6oqM5AuA3kcd+OALLcgCuLADrwRuT4tcnoHjctZlbkbs1qrjjuxWtHVPPBhm+mX5dxg9C0DL1nQ12iPV3qH2+zCilJBuMS+EAzH6y3lS7NHPR3VUy8rXzIR1DYRuodBl80UBi+15KWMzEQrcaO2rmLelfLiIMM7KgveTs7v/c28eqtsA8f3MfY2819xXP3AyWaFPJv69F4Oa6U+XGgENFJcj/TJw9YTBx6NyktCysN71RYHYQBW2Wocou6A84ZxX25hkMIAsz6Mb+gtzAVKl6Qlf6KgbsXj5vOAxfwcZZ4bL2z92WfAMZu6iIAjMgaMdxKPnvirW2ulzpK4VFPtM65a1aVCtfF3Xgnq9HKRCKiqcZeL2NPo6HrOnryKlTpFvmsxFqsUA6bO6WwYMLHhYIjahPwUYproIoxXZ25Z8tRxk8WIvKaLIFoVSRRhxdgCsXUt2+XIS2XFvLY/tgHy7mAs2vPaCous32WZvwHwyyX01wBfI9LrtjdJvAGINwbwbb2zhYDC3QPt/2zZ/1Mk+fnOf7b7gzz+Y9jh8f/dw/2Pe0kb9//uef3jPeL/1+FLbZjIaQod994gXIscu28b3vWanBr83fW6nFQCtauTGGhSXuktCxpdnHwb8+FB55AeTdqC/2HgOC6LEn7t9yRxZvQOgSDbzn8Oe0r837CP8d+DQ/z3ftJjjP8I+Z5THgFyGThnmRL+wJVw76Eg9wgDSfeDwc/72ZehIOihobu3h1CNzf2/bfzLTVGbb4p+pvjfTr+djf9eG+O/Or3O8DD+95Eey/i/4wZ/vhagAggTax/50TYFS9Ti9SiyLZSgoZWnXkV6V0su31jM7nHS69njOcWXFkRGfU07REagjZ/twaV+7giPyNTyGC1+5ENPhUX48M/uxct6O0Ohugab+sFyfPxpC/5nO5Uw0PjgBS3ZeRrYZv/1h7n91+scc/vvcP/3ftIjw/8UQ5zAvqGRcOz/l6W36e5yRCRXbNBh1N6GFp8Ivy2CtOBGrFD+BtxkHrZZflMAwrpGPLYjbFvGP0buyCiFz7f+1z0+zsd/t83j/zsH/28v6ZGOf3WR/a7jvrSC/oWOgCGhtbH+YRKFAQOOOJMG2m6U4XXDG0txa2xExFOtJthehlbI637XHzWQO0kwBIKFUfvRt12opZ7ytx+V61XLrGek9ZGIYv/0rYTct+KU3GMDyK88bcV/EaRzr29BbsH/43aP4/+w2x4M29z+a3cO33/cT3os+L8G5Ln2/fXOfVUQWTlPshY/pxGgMOTyHAOPqPBIO/Ltrx/1NLQMIPP69FJ/ruM7ffTxY10o3adPn/79bd6ApiFyjRm0PM8QViE/jGTIU8SGPAGzE99qXF3Od2NWxDrxF6w5DByDa0EWSMtPAtXJJ+sRJbigSXWZ3mZVyCYqa8XQML30gRD1uAQIQRDVd2potXFGzowFGICM5Pc7IeFKcFWqmFb53B2MwZpQql75mo9s7VyYCDXRo/hClFJCUw0Z+tow2lR0kYj6LEZH1gV1VqNddxpoNbxtCi9dz4EaxFpQrOKewr02EHqHpbuvPDWz/1Lb/25m4Pb4n47i/w9x/6d/fFj/20t6LPZfo8+hlC/4KhuK6a1Uu9uLG86+7tdyXDeFppKozKQVU3NNmHJ1bm1woPewgfO1py34vwyt+/n+mLbgf7fd65e+/zvsDvsH/N9HeqT4j3on7GenhPk1F9e2lh1dTgTv5G21l4Fzkt1W+1dbP8icHu6XZIfj667IweeVa3JyH2HnZlamH+wIcY2wehOA+mTU2JnLl7RlSc6pcuwOHrr5aQ0jf5UdXfhmzY0KtXwvXP9ErA2oWfOn6zjvtBtc/FKtzfpQV1v29F61lYZGhtWOeKhmL78ruJrbCtd/1u1Lg9Qhfba0Zf6Xyxyfdf2/120fl77/0O4c7v/cT3os839hcttwU34eyfda3o//i1DR08J5uEdziXONg7Z2xdWd+UFUvN6r8THI8tdwxIdrDdsycMF6pwON/NO12eETZRqQYCDvg77T+Rr8MkOp2YJ9fm2K6MN0/peeb35Y7s4HaNLC2w04uegqTldz6vwzDNRYdpD3PMcu68u29UPiO55sSfbhD2HjBGF20hg/dXB6dX5yfY4fsfj58gx/yQ8tSAOw5kMYRdNQfrSho74tftBB/ThGxZBJ8T7gN3+Xz3sXn25cbhjU6M/GGrP+KVdaeXGnepnr0PPplF9nTt4EPn3rn0Wrq0ScrcwQ54ouXXqbyTLrJWlqR9T1l4HN+yu1fi+mbyh1eHzZHQcFGGV/2UEBvD+mQbH+qya7DpPN3z05DJyHGzhf2gT6j0619v9SaNi9F/5k2mz/d3rDIdr/w8Gw3e4POmD/dwaH8997SkdEngARl9iJQx51M4imiZsl+SpO+r3sEaFJBGBtiFBnM7yZmQ5dZvfQGPJejlYkZpb8hppWHjnQWhN5GCp3UwJWBPElILRY3zoieFg5Amhi/EQKZ43g57pv5wGj2Q3JrnjNL/bBNTOJTyZfXJuBpb1smx3zWJeNU29fJb/+W0METSuCzLqWTqOFh1ouw+weZr6Tkh2YqWsgya9W1/LbnbuaVtzwGfHWjkNqo9/E8KYXoAjuWGoJELk3S9g8SDyHTKC53DNAG0L8yu4rOiLqBchxAPDt4P+QxxK5kuOC35/E8teQk5/vCaZ1pZBYAgYEz3sxJUAAssTcR5T+CnYJcPMcWsAJwd8zVAjkGMpipAQSTiWd3TOdOXIoccVbWS8gJVNVOOhVlXwmZCUUKgamilAc8V0cXsUvc+qLU1LP13eqoM6ekwhFB+xgy8VqqVBFOWurzDFT6SlxDKtO1IXmcCW9g7TjlCi8kIOEZiqQyZzbGXp2lWLsMX6To05YAu7/B61wZwn0Rv71oA29ITIR/KpRM12tCECl8PkVTdOKF4bzMaBVLyzmz4/IlMkvNHVhTsNRXLngl8epXUbu0vXojJ6jRSkvQBedfgQ2cShuieer4EdgNzmAruKXQU5evYJf6SVkVzAf4aoNW4FQFlJs8DrxTxiYafi6+PBnhssuHcld5kWIyCr50aiLSy014zvtbr9dgwJa4eY6z124adTVgt9dNCL9ly6fJHgsu3xnhwmQXBTztV+7mibDmDBbMWAq04TsGkNgvHCWUShbdeTIU5PQVP5n+VyAMslo4L7kNTtZlYX9Dc60eCLuC9Jxa0nntKEoCDLmBjA/d8m/oTmS77DXil84DBP0YoQE+GcOj6TzAVOUP6MKkRG55ts/P7ozGEDX8PpKSlQr7GEURNpFkSJRZdtBVsJ7AHRzIf/OivQHvEx12yCtD7VN0wo3vaEiqHek4WSZXc/GtURiB9Zecn7EVFJ1TngxmKGy+DUiPpgDsyi2BH/hHZhs1GqhmTELuKUhVwVBYxaWPce9ohW+locR/g7ze/d/zO7RpRWBWQAuLCi5/xyqAfDguGfzO9kSOxYQk6lGesk7kfMD4deimjCBihu8UubEcVoJpSybTOP/b+9aehu3gfA9v0JYH/qyrDixXTs3N9mDsQESxNj76uVEiCwZlvOqkf/ebx4kJdlNURTYPVQ87DoSNRwO5/ENKZFwREA6ZNOHJIXUSXuj1Qvq/s3i6tKbQ029zwYgec2pzZ4xVv8FCMR9g8s7aJ0cnB+kJG+35TOqb5vE6OQE+qg4eiPvZM4MOhb9oE2yHzewTViQ5zbbyqB5fp7ap6CQKhkaeTqo7gxNv6oVKTPLGJhRskv6BYvCv0WWQLRhpvsRa1WZA/EWVy1WhTS9HvlKcabJcZ8qo1JcbmF+m7KwIQ4OgJDWzsjLSUIpkJsgqiys2izMImHkcciZhuIfxV3Pg1+vvNsvl58NR9Q2zbMrIdob0MTHWocE57Y7hT7A/8Aavt5d/8A+LUuYCTNkblTAHhueR3rJ8iSGbVXWHfw6oENReEdxXRcOhNkAITaPwvhR5yCkb1+3ebvbphUP95xYEw9IPiRMCNBD/Rm8pHnuPxblSxGIxvrNLiUZFBp28cazZTL1g+7JifT1dqsqXxSMEdLlY0Z5SbZ6czGMduKVuzd4nGoICa6n0vyoNgBAXAuJ9HL4HeTQsES6KM5AnCGGmS75dMIk5W2vb+wfBUwt5SjIOX9SJ3M9njmFktxgVsTlmn5sXZBit2H85O4h5KHLyXWs4Y2hLuKBQ1XIeJ0MlJ+/9/NS1b8vg11Z5lVgH6UIEDwPe0KBW3cdJOfqRnwOJlfpNoWIpH01YX3bgLilR1VbbRL3hYRz98ecfSmEc0QklXN9DGDp3XRYRPo8HIi53dmGTRfvAbWfogGkF7hX+LkzUV5GAcWv6QCKDCroHh8OVEEmvevh6XBku2mpUxQlRMwrSZzk1IbZ5TfKIAHnTAA6Y2xKnbkSW0PC3W7rxFOlmYx0Fegs+ak6yB4lZhCcqghuX869iGd7yeg36ZqEuoZCmCj8zPpvM0rwk/FSIeIsGCMTPRFLupzrrLEMp8AFHj3OWeJwEMNFPKZv7t0RYbbNyMn3GiDh+oMBqnerOUS9qyfW0COsRNuwiP8MWoMTZOQlquBsPPP4Jysv3JWXZs1R3r1wuhsSvAGwBRL0St71Q0cugXsNkySjS2Gua6HGpbuRt0kT2bvdKen9KI2wOfXwAaFWyvGfaEkaqcdNHEU7qORiBzBY7eDEnmJwT7fb1fUdY97unjuRRJWK1p+hVNf1vXb/DXylo4X4Kx7yaQ0qH03tW55kKL4jQ0c2FRbJIycIjaiRRCEapOGaU7q+V7IHRiUNGqyRDrxQ/AWOMGEmTQZMt/a1zj+3o1/PeD9TV/vc31/MUzdXNxcG9TchMZTDoA1SOgpf1n+4bXBsKzDI9VOhYbnOo/l2pzk4egYKkk7aWGVTZuqP9bpZOzF5bc+F+RoRwmcCTPqaxpDECorVahBOqfvkZggBtn33fk+K9P7uyw/WKLtAR9tM33ILNnbW2qe7VhKmR2gmyVbwoB69dMC39ntH5/3d+w0XHGONti7aTRiqdWNvt9j6VN2Nqxm/4j4rXu2xM82v5AgZpkXiu2+sPtGJCMtPhPs0pWPpQjfDKM+qB7EYI2EBmRoXaZ0MsFTZOJw7Veaul7p1AXcFYqIUooLmplvgp/pmzru8clHDErjZqAvUIWT03DwYz9Zd7GySpuNuptA4c9zvG8+5ldlmComEcwHoHlY8EWfe9AHgT1M45TUI2idSJBtZ/FBL2iApICkJ89w+3yBlG5yw4TKgkETBiozj9ze3h4BbKjjcCYHhINH7BnpIdbZCzG6HRX/k5T2t5LYmE+lJJOH8v3p7s36PVof48/qD53RSxeaGw9PzyXg1jf1kFoX+aLSa+dN0OvZ/Hw3TaRyfDlezmCarzPFA4mWi1KVAKhtkwVaccH67ozlSg9WzFjPehTebhueTaDLzJ+PZmT+anId+NDkd+8koHk/OV9PodDjp3ursSle60pWudKUrXelKV7rSla505f9S/gKTzmV4AMgAAA==
  values:
    replicas: 1
    priorityClass:
      name: gardener-system-100
    clients:
      - name: local
        clientId: local
    image:
      repository: europe-docker.pkg.dev/gardener-project/snapshots/gardener/extensions/oidc-apps-controller
      tag: latest
    imagePullPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    cacheSelectorStr: "observability.gardener.cloud/app in (plutono, prometheus-shoot, prometheus-cache, prometheus-aggregate, prometheus-seed)"
    webhook:
      objectSelector:
        matchExpressions:
          - key: "observability.gardener.cloud/app"
            operator: "In"
            values: ["plutono", "prometheus-shoot", "prometheus-cache", "prometheus-aggregate", "prometheus-seed"]
    vpa:
      enabled: true
    configuration:
      oauth2Proxy:
        sslInsecureSkipVerify: false
        insecureOidcSkipIssuerVerification: false
        insecureOidcSkipNonce: false
        oidcIssuerUrl: "https://dexidp:5556"
        scope: "openid email groups"
      oidcCABundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROakNDQWg2Z0F3SUJBZ0lVT3B4dzVnS0MxdDdYdW1abVVzNENIZW5kek1jd0RRWUpLb1pJaHZjTkFRRUwKQlFBd016RWVNQndHQTFVRUNoTVZaRzlqYTJWeU9uQnliM1pwWkdWeUxXeHZZMkZzTVJFd0R3WURWUVFERXdoTQpiMk5oYkNCRFFUQWVGdzB5TkRBeU1qSXlNVEUwTURCYUZ3MHlPVEF5TWpBeU1URTBNREJhTURNeEhqQWNCZ05WCkJBb1RGV1J2WTJ0bGNqcHdjbTkyYVdSbGNpMXNiMk5oYkRFUk1BOEdBMVVFQXhNSVRHOWpZV3dnUTBFd2dnRWkKTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdElNR1R6cnN1cUdCbXByKzdidVdEU2o1Lwp2T3FwbDlwNWhsTWNUaWR1eHFpNmtyc2M5VWZDbmRKeEUvV0hDZW1POUlqWXRTVWtBeUtvSThuZjVTVlN3Q01rCndVZWVmVGVnK2laVUpseXdvTitGWHZUL1Uya2lYSXRDV2hNUUwvWmdjWS81OVROS2FCekdJZkY3MVY4TjVsM0kKSkVTbEt2UFliMnZvV2pYNXdiV1JteEkvSElTaEhaamhBK2htSkZBM3BBQnBQZUFvcmYvanB0YUxIdFgwQk44Qwp6N29uMmdYTzdsUVN2Sko0Y2F0SHdXeFRTQjhPRncwNXZiQzBTaVlmVVdUSmc0bFJucTZhazhicDFBd01TVGpIClUwMGJzU2ZXL0syeVNmSVhMMENHdFVvbG45K05icjdIU3ZvbHRYaXp2MWd1UHR4ZFV6V2t1ZGlqc3prckFnTUIKQUFHalFqQkFNQTRHQTFVZER3RUIvd1FFQXdJQkJqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01CMEdBMVVkRGdRVwpCQlRIZ2lvcjhzR1hweHExTCtwblpqRS9wNTl2M2pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWxBZGVwZjZICkFNSjFMOWliT3JONjV1RmVISFJPUTZTR3BjUURxdXBqUG1CU3Y1SGJsb2kreTlWalE1eDQ2dUtRdGoyTWJlTGUKVGhrRnA5ditsYkk3U3JqRjd4R0tOckVHcVJzanJzdGhmb2FDdkZQU3QxMWEyd0ZGeHdsVmsrTzNPWmNhRERaRgpNbXdGbmJmbXB2bHpyZzN4U2wxVkdnL3BiYmVzTGJoNTNyQk1ndldkcU5JYUtIWExoYXJSMXBYb1A3NjR6czhECmFQcnc4bFNxaXZqWXJJelZVUzllUDQwQTJLMU5vakJQVlB0dldXMXpySGMzb1c5SVZOS0EvaXFnMGNMdzYwN2kKblJ2NXdDcFlKTThKTDVYZEZ6N2NPTXNNUEUxaElYU1RDUnB6QnFZeUFFV1hEeXl2d1RmMHJBQmZzTDlzUVVQRQpYOTZFVVJsbWVsRW1nQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    targets:
      - name: "shoot--plutono"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "shoot--prometheus"
        namespaceSelector:
          matchLabels:
            gardener.cloud/role: shoot
        labelSelector:
          matchLabels:
            app: prometheus
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
      - name: "garden--plutono"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            component: plutono
        targetPort: 3000
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-seed"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: seed
            role: monitoring
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-aggregate"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: aggregate
            role: monitoring
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
      - name: "garden--prometheus-cache"
        namespaceSelector:
          matchLabels:
            project.gardener.cloud/name: garden
        labelSelector:
          matchLabels:
            name: cache
            role: monitoring
        targetPort: 9090
        ingress:
          create: true
          ingressClassName: "nginx-ingress-gardener"
          tlsSecretRef:
            name: "ingress-wildcard-cert"
            namespace: "garden"
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: oidc-apps-controller
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline
spec:
  deployment:
    deploymentRefs:
    - name: "oidc-apps-controller"
    policy: Always
---
