#!/usr/bin/env bash
# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
# SPDX-License-Identifier: Apache-2.0

set -x
"$(dirname $0)"/hack/prepare_release "$(dirname $0)"/.. github.com/gardener oidc-apps-controller