# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
# SPDX-License-Identifier: Apache-2.0

name: Build
on:
  push:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      mode: snapshot
    secrets: inherit
    permissions:
      contents: write
      packages: write
      id-token: write

  component-descriptor:
    uses: gardener/cc-utils/.github/workflows/post-build.yaml@master
    needs:
      - build
    secrets: inherit
    permissions:
      id-token: write
      contents: write
