# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
# SPDX-License-Identifier: Apache-2.0

name: Create Upgrade-Pull-Requests
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  upgrade-pullrequests:
    uses: gardener/cc-utils/.github/workflows/upgrade-dependencies.yaml@master
    secrets: inherit
    permissions:
      contents: write
      id-token: write
